// Pinata configuration - keep your JWT here for demonstration purposes.
// NOTE: In production you may prefer environment variables or a secure secret store.
module.exports = {
  PINATA_JWT: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiIxYzgxYmE4Yi1iNjljLTQ4OTQtODBjNS0yZTAyMWY2NzY2NWYiLCJlbWFpbCI6InZpdmVramFuZ2FtOTc2N0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGluX3BvbGljeSI6eyJyZWdpb25zIjpbeyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJGUkExIn0seyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJOWUMxIn1dLCJ2ZXJzaW9uIjoxfSwibWZhX2VuYWJsZWQiOmZhbHNlLCJzdGF0dXMiOiJBQ1RJVkUifSwiYXV0aGVudGljYXRpb25UeXBlIjoic2NvcGVkS2V5Iiwic2NvcGVkS2V5S2V5IjoiNzNlM2I5OGNkZmMxN2RhODU1MjgiLCJzY29wZWRLZXlTZWNyZXQiOiI5YTllMjMyYWJjZGZjYzJkNzRjMzZlMDQ0MmVlYWFmZmRjMGE3MmJmNDU3ZmQ2Y2FmZWYwN2E1NmNlYzEzY2IyIiwiZXhwIjoxNzkzNDU3Mzc2fQ.khCMa7bL2-RBkvj8ILjAwZTN7WrEV8ZcadnRMW9I6m4'
};
